import { STORAGE_KEY, defaultState, dateKey, metrics, projection, validateImport } from './core.mjs';
import { questionGroups, horizons, habitIdeas } from './content.mjs';
import { evidence } from './evidence.mjs';
import { createSync } from './sync.mjs';
import { buildPersonalPlan } from './personal-plan.mjs';

const $ = (s, root=document) => root.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = v => v === '' || v === undefined || v === null ? null : Number(v);
const fmt = (v, digits=0) => v === null || v === undefined || !Number.isFinite(v) ? '—' : new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(v);
const money = v => v === null || v === undefined ? '—' : `${fmt(v)} ${{USD:'$',RUB:'₽',KZT:'₸'}[state.profile.currency]||esc(state.profile.currency)}`;
const icons = {
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 path:'<path d="M6 20c0-7 13-3 13-10 0-4-9-5-11-2"/><circle cx="7" cy="7" r="2"/>',
 leaf:'<path d="M20 4C8 2 2 9 6 16s15 1 14-12ZM5 21 16 9"/>',
 chart:'<path d="M4 3v17h17M8 15l4-5 4 2 5-7"/>',
 user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 book:'<path d="M12 5v16M3 3c4-1 6 0 9 2 3-2 6-3 9-2v16c-4-1-6 0-9 2-3-2-5-3-9-2Z"/>',
 arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>',
 heart:'<path d="M20 5c-3-3-6 0-8 2-2-2-5-5-8-2s-2 7 8 15C22 12 23 8 20 5Z"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
const nav = [['today','sun','Сегодня'],['roadmap','path','Мой маршрут'],['habits','leaf','Привычки'],['metrics','chart','Мой прогресс'],['self','user','Узнать себя'],['method','book','На чём основано']];
let context = null;
try { const r=await fetch('/private/context.json'); if(r.ok) context=await r.json(); } catch {}
let state = defaultState(), storageIssue='', corruptRaw=null, restored=false, recoveryRaw=null;
try {
  const saved=localStorage.getItem(STORAGE_KEY);
  if(saved) { state=validateImport(JSON.parse(saved)); restored=true; }
} catch(e) { storageIssue='Не удалось прочитать сохранение. Исходные данные не перезаписаны. Можно скачать их и восстановить резервную копию.'; try{corruptRaw=localStorage.getItem(STORAGE_KEY);}catch{} }
try { recoveryRaw=localStorage.getItem(STORAGE_KEY+'-recovery'); } catch {}
if(!restored && context?.seedProfile) state.profile={...state.profile,...context.seedProfile};
if(!restored && context?.seedAnswers) state.answers={...context.seedAnswers};
let validSnapshot=JSON.stringify(state);
let view=['today','roadmap','habits','metrics','self','method'].includes(location.hash.slice(1))?location.hash.slice(1):'today';
let selectedDate=dateKey(), horizon='week', questionGroup='direction', financeMonth=dateKey().slice(0,7), editingHabit=null;
let syncStatus={kind:'syncing',message:'Подключаем локальную базу'},sync=null;
function updateSyncStatus(status) {
 syncStatus=status;const el=$('#database-status');if(!el)return;
 const labels={saved:'Сохранено в базе',syncing:'Сохраняем в базу…',offline:'В браузере · база недоступна',conflict:'Нужно сверить версии'};
 el.textContent=labels[status.kind]||status.message;el.className=`database-status ${status.kind}`;el.title=status.updatedAt?`Последняя запись: ${new Date(status.updatedAt).toLocaleString('ru-RU')}`:(status.message||'');
 const conflict=$('#sync-conflict');if(conflict)conflict.hidden=status.kind!=='conflict';
}
try {
 sync=createSync({key:STORAGE_KEY,storage:localStorage,fetch:(url,options={})=>window.fetch(url,{...options,signal:AbortSignal.timeout(8000)}),onStatus:updateSyncStatus,onState:next=>{
   state=validateImport(next);validSnapshot=JSON.stringify(state);
   if(document.activeElement?.matches('input,textarea,select'))updateAnswerCount();else if($('#app').children.length)render();
 }});
 if(!corruptRaw){const loaded=await sync.start(state,{hasLocal:restored});state=validateImport(loaded.state);validSnapshot=JSON.stringify(state);}
 else syncStatus={kind:'offline',message:'Сначала восстановите повреждённое сохранение'};
}catch{syncStatus={kind:'offline',message:'База недоступна; локальные ответы сохранены'};}
window.addEventListener('storage',event=>{if(!corruptRaw)sync?.handleStorage(event);});
window.addEventListener('online',()=>sync?.flush());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')sync?.flush();});
function save(message='Сохранено на этом устройстве') {
  if(corruptRaw) { toast('Сначала восстановите данные из файла. Исходное сохранение защищено.'); return false; }
  let candidate;
  try { candidate=validateImport(state); } catch(e) { state=JSON.parse(validSnapshot); toast(`Изменение не применено: ${e.message}`); return false; }
  state=candidate;validSnapshot=JSON.stringify(state);
  try { localStorage.setItem(STORAGE_KEY,validSnapshot); storageIssue='';sync?.queue(state); toast(message); return true; }
  catch(e) { storageIssue=`Не удалось записать данные в браузер. Экспортируйте их, прежде чем закрывать приложение.`; toast(storageIssue); return false; }
}
function toast(message) { const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4000); }
function go(next) { view=next;location.hash=next;render();window.scrollTo({top:0,behavior:'smooth'}); }
const dayLabel = d => new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
const answered = () => questionGroups.flatMap(g=>g.questions).filter(([id])=>state.answers[id]?.trim()).length;
const coreQuestionsAnswered=()=>['success','values','freedom'].filter(id=>state.answers[id]?.trim()).length;
const questionTotal=questionGroups.reduce((n,g)=>n+g.questions.length,0);
function render() {
  const m=metrics(state);
  document.title=`${nav.find(n=>n[0]===view)?.[2]} · Путь маленьких шагов`;
  $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#today" data-view="today"><span class="brand-symbol">${icon('path')}</span><span>путь<span class="brand-sub">маленьких шагов</span></span></a><div class="side-caption">ЛИЧНОЕ ПРОСТРАНСТВО</div><nav aria-label="Главная навигация">${nav.map(([id,ic,title])=>`<button class="nav-item ${view===id?'active':''}" data-view="${id}" aria-label="${title}" ${view===id?'aria-current="page"':''}>${icon(ic)}<span>${title}</span>${id==='self'?`<span class="nav-count">${answered()}/${questionTotal}</span>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="side-note">Не нужно менять всё.<br>Достаточно следующего шага.<span>В своём темпе.</span></div><button class="profile-link" data-view="self"><span class="avatar">${esc((state.profile.name||'Я')[0])}</span><span>${esc(state.profile.name||'Мой профиль')}<small>Моя точка старта</small></span>${icon('arrow')}</button><div class="private-label">${icon('lock')} Данные на этом устройстве</div></div></aside><main><header class="topbar"><div class="breadcrumb">Мой путь <span>/</span> ${nav.find(n=>n[0]===view)[2]}</div><div class="top-actions"><button id="database-status" class="database-status syncing" data-action="sync-now" aria-live="polite">Подключаем базу…</button><span class="today-date">${new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</span><button class="icon-button" data-action="export" aria-label="Скачать резервную копию" title="Скачать резервную копию">${icon('download')}</button></div></header><div class="page"><div id="sync-conflict" class="notice warm" ${syncStatus.kind==='conflict'?'':'hidden'}><span>Найдены две версии одних и тех же данных. Обе версии сохранены. Выберите, какую использовать.</span><button class="text-button" data-action="sync-local">Оставить текущую</button><button class="text-button" data-action="sync-remote">Выбрать другую</button></div>${storageIssue?`<div class="notice error">${esc(storageIssue)} <button data-action="raw-export">Скачать исходные данные</button></div>`:''}${({today:todayView,roadmap:roadmapView,habits:habitsView,metrics:metricsView,self:selfView,method:methodView})[view](m)}<footer class="footer"><span>Маленькие шаги тоже ведут вперёд.</span><span>Путь · личный трекер</span></footer></div></main>`;
  updateSyncStatus(syncStatus);
}
function heading(kicker,title,description,action='') { return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`; }
function stat(label,value,caption,ic='chart') { return `<div class="stat-card"><div class="stat-label">${label}${icon(ic)}</div><div class="stat-value">${value}</div><div class="stat-caption">${caption}</div></div>`; }
function empty(text,action='') { return `<div class="empty-state">${icon('leaf')}<p>${text}</p>${action}</div>`; }
function todayView(m) {
 const entry=state.entries[selectedDate]||{}, active=state.habitPlans.filter(h=>h.active),done=active.filter(h=>entry.habits?.[h.id]).length;
 const isToday=selectedDate===dateKey();
 return heading('ДЕНЬ ЗА ДНЁМ',`${state.profile.name?`${esc(state.profile.name)}, ваш`:'Ваш'} следующий шаг.`, 'Больше ясности. Больше свободы. Больше своей жизни.',`<span class="pill">${icon('leaf')} В своём темпе</span>`)+`
 <section class="hero"><div class="hero-copy"><div class="eyebrow">ПУТЬ МАЛЕНЬКИХ ШАГОВ</div><h2>Большие перемены<br>начинаются с малого.</h2><p>Не идеальный день, а одно осмысленное действие.<br>Сегодня этого достаточно, чтобы двигаться.</p><button class="button primary" data-action="start">Мой маленький шаг ${icon('arrow')}</button><span class="hero-foot">${icon('clock')} Начните с 10 минут · ваш бюджет ${fmt(state.profile.dailyMinutes)} мин/день</span></div><svg class="path-art" viewBox="0 0 360 290" fill="none" aria-hidden="true"><circle cx="230" cy="93" r="72" fill="#d7e0c4"/><circle cx="230" cy="93" r="50" fill="#e6ecd9"/><path d="M15 295C-5 229 107 249 91 197S25 154 66 120 166 169 178 128 117 102 138 65 218 71 230 22" stroke="#cad6b7" stroke-width="26"/><path d="M15 295C-5 229 107 249 91 197S25 154 66 120 166 169 178 128 117 102 138 65 218 71 230 22" stroke="#f7faee" stroke-width="2" stroke-dasharray="5 7"/><circle cx="90" cy="197" r="11" fill="#345744" stroke="#eef3e3" stroke-width="5"/><path d="M229 24V5m0 0 20 7-20 6" stroke="#42634c" stroke-width="2"/><path d="m292 209 0-43m0 23c-25-1-21-23-21-23 23 0 21 23 21 23m0-5c25 0 21-22 21-22-21 0-21 22-21 22" stroke="#88a278" stroke-width="2"/><ellipse cx="291" cy="213" rx="26" ry="5" fill="#d1dcbe"/><text x="209" y="254" fill="#68845d" font-size="12" font-family="sans-serif" letter-spacing="2">ШАГ ЗА ШАГОМ</text></svg></section>
 <div class="stats-grid">${stat('Доход в месяц',money(m.financialRecord?.income),m.financialMonth?`Запись за ${esc(m.financialMonth)}`:m.financialRecord?.income!=null?'Исходная оценка · семейный доход уточнить':'Добавьте точку старта','chart')}${stat('Настроение',`${fmt(m.moodAverage,1)}<small> / 10</small>`,`Оценок за 7 дней: ${m.moodCount}`,'sun')}${stat('Энергия',`${fmt(m.energyAverage,1)}<small> / 10</small>`,`Оценок за 7 дней: ${m.energyCount}`,'leaf')}${stat('Ритм привычек',m.habitRate===null?'—':`${fmt(m.habitRate)}<small>%</small>`,'Выполнено от недельного плана','check')}</div>
 <div class="two-column"><section class="card steps-card" id="daily-steps"><div class="section-title"><div><div class="eyebrow">ОДНО ДЕЙСТВИЕ ИМЕЕТ ЗНАЧЕНИЕ</div><h2>Маленькие шаги ${isToday?'сегодня':dayLabel(selectedDate)}</h2></div><span class="counter">${done}/${active.length}</span></div><div class="week-strip" aria-label="Последние семь дней">${m.weekDates.map(d=>`<button class="day ${d===selectedDate?'selected':''}" data-date="${d}" aria-label="Запись за ${dayLabel(d)}" ${d===selectedDate?'aria-pressed="true"':'aria-pressed="false"'}><span>${new Date(d+'T12:00').toLocaleDateString('ru-RU',{weekday:'short'})}</span><strong>${Number(d.slice(-2))}</strong><i class="${Object.keys(state.entries[d]||{}).length?'logged':''}"></i></button>`).join('')}</div><div class="habit-checklist">${active.map((h,i)=>`<button class="habit-check ${entry.habits?.[h.id]?'done':''}" data-habit-check="${esc(h.id)}" aria-pressed="${!!entry.habits?.[h.id]}"><span class="checkbox">${entry.habits?.[h.id]?icon('check'):''}</span><span><strong>${esc(h.title)}</strong><small>${esc(h.cue)} · цель ${h.target} р./нед.</small><em>Лёгкая версия: ${esc(h.minimum)}</em></span></button>`).join('')||empty('Выберите первую привычку.',`<button class="text-button" data-view="habits">Выбрать привычку →</button>`)}</div><div class="card-bottom"><span>Пропуск — повод упростить, а не начать с нуля.</span><button class="text-button" data-view="habits">Настроить ${icon('arrow')}</button></div></section>
 <section class="card checkin"><div class="section-title"><div><div class="eyebrow">МИНУТА ВНИМАНИЯ К СЕБЕ</div><h2>Как вы ${isToday?'сегодня':'в этот день'}?</h2></div>${icon('heart')}</div><form id="checkin-form"><label class="date-label">Дата записи<input type="date" name="entryDate" value="${selectedDate}" max="${dateKey()}" required></label><div class="fields-grid">${scoreField('mood','Настроение','0 — очень плохое · 10 — отличное',entry.mood)}${scoreField('energy','Энергия','0 — совсем нет · 10 — много сил',entry.energy)}${scoreField('meaning','Осмысленность дня','0 — нет · 10 — очень осмысленный',entry.meaning)}<label>Сон, часов<input name="sleep" type="number" min="0" max="24" step="0.5" placeholder="Не отмечено" value="${esc(entry.sleep)}"><small>Оценка длительности сна</small></label></div><label>Работа над ростом дохода, минут<input name="focusMinutes" type="number" min="0" max="1440" placeholder="Не отмечено" value="${esc(entry.focusMinutes)}"></label><label>Что сегодня помогло или порадовало?<textarea name="note" maxlength="10000" rows="2" placeholder="Даже что-то совсем небольшое…">${esc(entry.note)}</textarea></label><button class="button primary full" type="submit">Сохранить день ${icon('check')}</button><p class="form-note">Можно заполнить только часть. Пропуск не равен нулю.</p></form></section></div>
 <section class="bottom-banner"><span class="round-icon">${icon('path')}</span><div><h3>${coreQuestionsAnswered()<3?'Хороший маршрут начинается с вас.':'От сегодняшнего шага — к большой цели.'}</h3><p>${coreQuestionsAnswered()<3?'В анкете 56 вопросов. Начните с трёх — остальное может подождать.':'Неделя, месяц, полгода, год и пять лет. С понятным результатом на каждом этапе.'}</p></div><button class="button secondary" data-view="${coreQuestionsAnswered()<3?'self':'roadmap'}">${coreQuestionsAnswered()<3?'Узнать себя':'Мой маршрут'} ${icon('arrow')}</button></section>`;
}
function scoreField(name,label,hint,value) { return `<label>${label}<select name="${name}" aria-label="${label}"><option value="">Не отмечено</option>${Array.from({length:11},(_,i)=>`<option value="${i}" ${value===i?'selected':''}>${i} / 10</option>`).join('')}</select><small>${hint}</small></label>`; }
function roadmapView() {
 const h=horizons.find(x=>x.id===horizon), count=h.steps.filter(s=>state.milestones[s.id]).length;
 const lastReview=state.reviews[dateKey()]||{},personalPlan=buildPersonalPlan(state,context);
 return heading('НАПРАВЛЕНИЕ, А НЕ ГОНКА','Мой маршрут.','Большая цель задаёт направление. Следующий шаг остаётся маленьким.')+`
 <div class="goal-ribbon"><span>${icon('path')} ${state.profile.goalScope==='family'?'Семейный':'Личный'} ориентир</span><strong>${money(state.profile.goalAmount)} ${state.profile.goalKind==='capital'?'капитала':'дохода в месяц'}</strong><span>к ${new Date(state.profile.goalDate+'T12:00').toLocaleDateString('ru-RU')}</span><button class="text-button" data-view="self">Уточнить цель →</button></div><div class="horizon-tabs" role="group" aria-label="Горизонт планирования">${horizons.map(x=>`<button class="${x.id===horizon?'active':''}" data-horizon="${x.id}" aria-pressed="${x.id===horizon}">${x.label}</button>`).join('')}</div>${personalRouteView(personalPlan)}<details class="general-route space-top"><summary>Базовый список действий на этот горизонт</summary><section class="route-intro"><div><div class="eyebrow">${h.eyebrow}</div><h2>${h.title}</h2><p>${h.description}</p></div><div class="route-progress"><strong>${count}<span> / ${h.steps.length}</span></strong><small>ориентира пройдено</small></div></section><div class="route-list">${h.steps.map((s,i)=>`<article class="route-step ${state.milestones[s.id]?'complete':''}"><span class="step-number">${String(i+1).padStart(2,'0')}</span><div><h3>${s.title}</h3><p>${s.text}</p><div class="criterion">${icon('check')}<span><b>Готово, когда:</b> ${s.criterion}</span></div></div><label class="milestone-toggle"><input type="checkbox" data-milestone="${s.id}" ${state.milestones[s.id]?'checked':''}><span>Готово</span></label></article>`).join('')}</div>
 </details>${focusView()}<section class="card weekly-review"><div class="section-title"><div><div class="eyebrow">РАЗ В НЕДЕЛЮ · 15 МИНУТ</div><h2>Пауза, чтобы выбрать следующий шаг</h2></div><span class="pill">${dayLabel(dateKey())}</span></div><form id="review-form"><div class="three-column"><label>Что сработало?<textarea name="win" rows="3" maxlength="10000" placeholder="Маленькая победа этой недели">${esc(lastReview.win)}</textarea></label><label>Что оказалось трудным?<textarea name="hard" rows="3" maxlength="10000" placeholder="Без обвинений. Что можно упростить?">${esc(lastReview.hard)}</textarea></label><label>Мой один следующий шаг<textarea name="next" rows="3" maxlength="10000" placeholder="Конкретное действие, время и место">${esc(lastReview.next)}</textarea></label></div><div class="fields-grid">${scoreField('satisfaction','Удовлетворённость жизнью','В целом сейчас: 0 — совсем нет · 10 — полностью',lastReview.satisfaction)}${scoreField('autonomy','Ощущение выбора','0 — нет выбора · 10 — живу по своему выбору',lastReview.autonomy)}</div>${marketReviewFields(lastReview)}<button class="button primary" type="submit">Сохранить обзор ${icon('check')}</button></form><details><summary>Прошлые обзоры (${Object.keys(state.reviews).length})</summary>${Object.entries(state.reviews).sort((a,b)=>b[0].localeCompare(a[0])).map(([d,r])=>`<div class="review-history"><b>${dayLabel(d)}</b><p>${esc(r.win)||'Победа не записана'}</p><p class="muted">Трудность: ${esc(r.hard)||'—'}</p><p>Следующий шаг: ${esc(r.next)||'—'}</p><small>Удовлетворённость: ${fmt(r.satisfaction)} / 10 · Выбор: ${fmt(r.autonomy)} / 10</small><p class="muted">Разговоры: ${fmt(r.conversations)} · Предложения: ${fmt(r.offers)} · Оплаты: ${fmt(r.paidPilots)}</p><p>${esc(r.output)}</p></div>`).join('')}</details></section>`;
}
function habitsView() {
 const active=state.habitPlans.filter(h=>h.active).length;
 return heading('МАЛЕНЬКОЕ, ПОВТОРЯЕМОЕ, СВОЁ','Привычки без давления.','Начните с одного шага для роста и одного для восстановления.',`<button class="button primary" data-action="new-habit">${icon('plus')} Своя привычка</button>`)+`<div class="notice">${icon('leaf')}<span>Активно: ${active}. ${active>3?'Если стало тяжело, оставьте 1–3 привычки.':'Привяжите действие к знакомому событию и придумайте лёгкую версию.'} Привычка не обязана появиться за 21 день.</span></div><div class="habit-grid">${state.habitPlans.map(h=>`<article class="card habit-plan ${h.active?'':'paused'}"><div class="section-title"><span class="round-icon">${icon(h.id==='focus'?'chart':'leaf')}</span><span class="pill">${h.active?'В моём ритме':'На паузе'}</span></div><h2>${esc(h.title)}</h2><dl><dt>Когда</dt><dd>${esc(h.cue)}</dd><dt>Если мало сил</dt><dd>${esc(h.minimum)}</dd><dt>Посильная цель</dt><dd>Раз в неделю: ${h.target}</dd></dl><div class="habit-actions"><button class="text-button" data-edit-habit="${esc(h.id)}">Настроить</button><button class="text-button" data-pause-habit="${esc(h.id)}">${h.active?'Поставить на паузу':'Возобновить'}</button></div></article>`).join('')}</div><div class="section-title space-top"><div><div class="eyebrow">МОЖНО ПОПРОБОВАТЬ</div><h2>Меню маленьких действий</h2></div></div><div class="ideas-grid">${habitIdeas.filter(h=>!state.habitPlans.some(p=>p.id===h.id)).map(h=>`<article class="idea-card"><h3>${h.title}</h3><p>${h.reason}</p><small>${h.target} р./нед. · есть двухминутная версия</small><button class="text-button" data-add-habit="${h.id}">Добавить ${icon('plus')}</button></article>`).join('')||'<p class="muted">Все идеи уже добавлены. Оставьте активными только посильные.</p>'}</div><dialog id="habit-dialog"><form id="habit-form"><div class="section-title"><h2>Моя маленькая привычка</h2><button type="button" class="icon-button" data-action="close-dialog" aria-label="Закрыть">×</button></div><label>Что я буду делать<input name="title" required maxlength="150" placeholder="10 минут над одним рабочим кейсом"></label><label>После какого события<input name="cue" required maxlength="200" placeholder="После утреннего кофе"></label><label>Лёгкая версия на трудный день<input name="minimum" required maxlength="200" placeholder="Открыть проект и сделать один маленький шаг"></label><label>Сколько раз в неделю<input name="target" required type="number" min="1" max="7" value="4"></label><button class="button primary full" type="submit">Сохранить привычку</button></form></dialog>`;
}
function metricsView(m) {
 const r=state.finances[financeMonth]||(financeMonth===dateKey().slice(0,7)&&!Object.keys(state.finances).length?state.profile:{}), p=projection(state.profile,m.financialRecord), hasMoney=Object.keys(state.finances).length;
 return heading('НАБЛЮДАТЬ, ЧТОБЫ ВЫБИРАТЬ','Мой прогресс.','Ваши деньги и ваше состояние. Два результата, которые важно видеть рядом.')+`
 <div class="stats-grid">${stat('Чистый капитал',money(m.netWorth),'Активы минус все обязательства')}${stat('Свободные деньги',money(m.monthlySurplus),'Чистый доход минус расходы за месяц')}${stat('Доля сбережений',m.savingsRate===null?'—':`${fmt(m.savingsRate,1)}%`,'Свободные деньги / чистый доход')}${stat('Запас ликвидности',m.runway===null?'—':`${fmt(m.runway,1)}<small> мес.</small>`,'Доступные средства / месячные расходы','leaf')}</div>
 <div class="two-column"><section class="card"><div class="section-title"><div><div class="eyebrow">КАЧЕСТВО ЖИЗНИ</div><h2>Как меняется состояние</h2></div><span class="pill">14 дней</span></div>${moodChart()}<div class="chart-legend"><span><i></i>Настроение, 0–10</span><span>Только ваши наблюдения</span></div><p class="form-note">Разрывы — дни без оценки. По такому графику нельзя установить причины изменений.</p><div class="mini-stats"><div><strong>${fmt(m.meaningAverage,1)} / 10</strong><span>Смысл · оценок за 7 дней: ${m.meaningCount}</span></div><div><strong>${m.focusCount?fmt(m.focusMinutes):'—'} мин</strong><span>Работа над доходом · 7 дней</span></div></div></section><section class="card projection-card"><div class="eyebrow">ФИНАНСОВЫЙ ОРИЕНТИР</div><h2>${money(state.profile.goalAmount)}</h2><p>${state.profile.goalScope==='family'?'Семейный':'Личный'} ${state.profile.goalKind==='capital'?'чистый капитал':'доход в месяц'} к ${esc(state.profile.goalDate)}</p>${p?`<dl class="projection-list"><dt>До цели</dt><dd>${p.months} мес.</dd><dt>Осталось</dt><dd>${money(p.gap)}</dd><dt>${state.profile.goalKind==='capital'?'Нужно добавлять в месяц':'Целевой месячный доход'}</dt><dd>${money(p.requiredMonthly)}</dd><dt>При текущем темпе</dt><dd>${money(p.projected)}</dd></dl><div class="notice ${p.possible?'':'warm'}">${p.possible?'Текущий расчётный темп соответствует цели. Пересматривайте его по фактическим данным.':'Текущий темп пока не приводит к цели. Следующий шаг — проверить способ увеличить свободный денежный поток.'}</div>`:`<div class="projection-empty">${icon('path')}<h3>Сначала точка старта</h3><p>Запишите активы, долги, доход и расходы в ${esc(state.profile.currency)}. Неизвестный долг оставьте пустым.</p></div>`}<p class="form-note">Сценарий без доходности, изменения цен и курсов. Не прогноз и не инвестиционная рекомендация.</p></section></div>
 ${latestReviewView()}${assetDraftView()}
 <section class="card space-top"><div class="section-title"><div><div class="eyebrow">ОДНА ЗАПИСЬ В МЕСЯЦ</div><h2>Мои финансовые данные</h2></div><label class="inline-label">Месяц<input type="month" id="finance-month" value="${financeMonth}" max="${dateKey().slice(0,7)}"></label></div><p class="muted">Все суммы в ${esc(state.profile.currency)}. Охват: ${state.profile.goalScope==='family'?'семейный':'личный'}. Учитывайте доходы и расходы в этом же охвате. Переводы между своими счетами не считаются доходом.</p>${context&&!hasMoney?`<p class="form-note">Исходные ${money(state.profile.income)} — указанная вами приблизительная оценка дохода. Уточните полный семейный доход после налогов и месячные расходы. Качественные оценки сбережений пока не заменены точной суммой.</p>`:''}<form id="finance-form"><div class="three-column">${financialField('income','Доход после налогов',r.income,'Доход за месяц, не годовой')}${financialField('expenses','Все расходы за месяц',r.expenses,'Включая обязательные платежи')}${financialField('assets','Стоимость учитываемых активов',r.assets,'Только доли, которые входят в вашу цель')}${financialField('debts','Остаток всех обязательств',r.debts,'0 — долгов нет; пусто — неизвестно')}${financialField('liquidAssets','Из них доступные ликвидные средства',r.liquidAssets,'Без стоимости недвижимости')}</div><button class="button primary" type="submit">Сохранить месяц ${icon('check')}</button></form>${hasMoney?`<div class="table-wrap"><table><thead><tr><th>Месяц</th><th>Доход</th><th>Расходы</th><th>Капитал</th></tr></thead><tbody>${Object.entries(state.finances).sort((a,b)=>b[0].localeCompare(a[0])).map(([month,f])=>`<tr><td><button class="text-button" data-finance-month="${month}">${month}</button></td><td>${money(f.income)}</td><td>${money(f.expenses)}</td><td>${money(f.assets!=null&&f.debts!=null?f.assets-f.debts:null)}</td></tr>`).join('')}</tbody></table></div>`:''}</section>
 <details class="card space-top"><summary>Как считаются показатели</summary><div class="definitions"><p><b>Капитал:</b> стоимость учитываемых долей активов минус долги. Квартира и наличные различаются по ликвидности.</p><p><b>Доход:</b> фактически полученный чистый доход. Рост оценивайте по нескольким месяцам, особенно при нерегулярных поступлениях.</p><p><b>Свободные деньги:</b> доход минус расходы. Отрицательное значение означает дефицит, а не ошибку.</p><p><b>Запас ликвидности:</b> доступные ликвидные средства / все месячные расходы. Это упрощённая оценка; недвижимость не включается в числитель.</p><p><b>Ритм привычек:</b> выполненные действия относительно выбранной частоты за последние 7 дней, с ограничением 100% для каждой привычки. В начале пути знаменатель ограничен прошедшими днями. Пауза и изменение частоты меняют текущую оценку.</p><p><b>Самочувствие:</b> средние только по заполненным ответам за 7 дней. Это авторские вопросы, не психологический диагноз и не валидированная шкала.</p></div></details>`;
}
function financialField(name,title,value,hint) { return `<label>${title}<input name="${name}" type="number" min="0" max="1000000000000" step="0.01" value="${esc(value)}" placeholder="Неизвестно"><small>${hint}</small></label>`; }
function focusView() {
 const tracks={
   service:{name:'Техническая услуга',why:'Проверить, готовы ли платить за небольшую понятную пользу: автоматизацию отчёта, настройку или техническую проверку.',steps:['Дни 1–3: выбрать одну повторяющуюся проблему и описать, кому вы помогаете.','Дни 4–7: провести 3 разговора о текущем процессе, потерях времени и решениях.','Дни 8–10: собрать маленькое демо на вымышленных или разрешённых данных.','Дни 11–14: предложить ограниченный платный пилот с результатом, сроком и ценой.'],criterion:'3 разговора, 1 демо, 1 конкретное предложение. Оплата — отдельный результат, не обещание.'},
   career:{name:'Рост в профессии',why:'Использовать накопленный опыт, чтобы проверить более высокую оплату своей работы.',steps:['Дни 1–3: выбрать целевую роль и изучить 10 актуальных вакансий.','Дни 4–7: сопоставить требования с опытом и выбрать один подтверждающий кейс.','Дни 8–10: описать кейс через проблему, действие и измеримую пользу.','Дни 11–14: сделать 3 качественных отклика или договориться о разговоре о росте.'],criterion:'10 вакансий, 1 кейс, 3 отклика или 1 предметный разговор. Оффер учитывается только после получения.'},
   product:{name:'Свой продукт',why:'Продолжать один проект только после проверки реальной потребности и согласованного результата.',steps:['Дни 1–3: выбрать один проект и записать, кому и какую проблему он решает.','Дни 4–7: уточнить проблему в 3 разговорах; отделить интерес от готовности платить.','Дни 8–10: согласовать минимальный пилот, стоимость, ресурсы и критерий приёмки.','Дни 11–14: показать минимальное решение и получить конкретную обратную связь.'],criterion:'Есть подтверждённая проблема и решение о пилоте: согласован, изменён или остановлен.'}
 };
 const selected=state.answers.focusDirection||context?.currentPlan?.direction||'',track=tracks[selected];
 return `<section class="card focus-plan space-top"><div class="section-title"><div><div class="eyebrow">ПЕРВЫЕ 14 ДНЕЙ · ОДИН ЭКСПЕРИМЕНТ</div><h2>За что рынок готов платить?</h2></div><span class="pill">${state.profile.dailyMinutes} мин/день</span></div><p class="muted">${context?'Ваш опыт в IT, автоматизации и организации работы — хорошая исходная гипотеза. Начните с существующей компетенции.':'Выберите направление, в котором уже есть опыт или доступ к реальным задачам.'} Новые идеи можно записать в анкету и вернуться к ним после эксперимента.</p><div class="track-choices">${Object.entries(tracks).map(([id,t])=>`<button data-focus-track="${id}" class="${selected===id?'active':''}" aria-pressed="${selected===id}">${t.name}</button>`).join('')}</div>${track?`<p class="focus-why">${track.why}</p><ol class="focus-steps">${track.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="criterion">${icon('check')}<span><b>Критерий:</b> ${track.criterion}</span></div>`:'<p class="form-note">Выбор меняет этот двухнедельный план. Его можно пересмотреть после первого обзора.</p>'}<label class="space-top">Моя гипотеза и следующий шаг<textarea rows="2" data-answer="experimentPlan" maxlength="10000" placeholder="Помогаю [кому] решить [проблему]. На этой неделе проверю это через…">${esc(state.answers.experimentPlan)}</textarea></label><p class="form-note">Ритм на обычный день: ${Math.max(2,state.profile.dailyMinutes-15)} мин на одну рабочую задачу, до 10 мин движения, 2–5 мин на отметку. В трудный день достаточно лёгкой версии привычки. Один день недели оставьте для обзора и отдыха.</p></section>`;
}
function marketReviewFields(review) {
 return `<div class="review-market"><h3>Внешний результат недели</h3><p class="form-note">Считайте реальные действия отдельно. Один разговор нельзя одновременно считать оплаченной продажей.</p><div class="three-column">${[['conversations','Содержательные разговоры'],['offers','Конкретные предложения'],['paidPilots','Оплаченные пилоты / заказы']].map(([name,label])=>`<label>${label}<input name="${name}" type="number" min="0" max="1000000" step="1" value="${esc(review[name])}" placeholder="Не отмечено"></label>`).join('')}</div><label class="space-top">Что можно показать: результат, польза, ссылка<textarea name="output" rows="2" maxlength="10000" placeholder="Одна законченная работа или подтверждённый результат">${esc(review.output)}</textarea></label></div>`;
}
function latestReviewView() {
 const item=Object.entries(state.reviews).filter(([d])=>d<=dateKey()).sort((a,b)=>b[0].localeCompare(a[0]))[0];
 if(!item)return `<div class="notice">${icon('path')}<span>В недельном обзоре можно отмечать разговоры, предложения, оплаты, удовлетворённость жизнью и ощущение выбора. <button class="text-button" data-view="roadmap">К обзору →</button></span></div>`;
 const [d,r]=item;
 return `<section class="card market-result space-top"><div class="section-title"><h2>Что изменилось за неделю</h2><span class="pill">Обзор ${dayLabel(d)}</span></div><div class="result-row">${[['Разговоры',r.conversations],['Предложения',r.offers],['Оплаты',r.paidPilots],['Удовлетворённость / 10',r.satisfaction],['Ощущение выбора / 10',r.autonomy]].map(([label,value])=>`<div><strong>${fmt(value)}</strong><span>${label}</span></div>`).join('')}</div>${r.output?`<p class="muted space-top">${esc(r.output)}</p>`:''}</section>`;
}
function personalRouteView(plan) {
 const f=plan.financial,usd=v=>v===null||v===undefined?'—':`${fmt(v)} $`;
 const average=f.goalGap!==null&&f.totalMonths>0?f.goalGap/f.totalMonths:null;
 const selected=plan.milestones.filter(x=>x.horizon===horizon);
 return `<section class="personal-route"><div class="personal-route-heading"><div><div class="eyebrow">ВАШ ПЕРСОНАЛЬНЫЙ ФИНАНСОВЫЙ МАРШРУТ</div><h2>${f.eligible?`От вашей точки старта — к ${usd(f.goalAmount)}`:"Ваш маршрут действий"}</h2><p>${f.scope==='family'?'Семейный':'Личный'} капитал: недвижимость и деньги за вычетом долгов. Доход, капитал и ликвидные средства считаем отдельно.</p></div><span class="pill">${esc(plan.planStartDate)} → ${esc(plan.goalDate)}</span></div>${f.limitation?`<p class="form-note">${esc(f.limitation)}</p>`:''}${f.eligible?`<div class="plan-stats"><div><span>Исходная оценка капитала</span><strong>${usd(f.startingCapital)}</strong><small>${f.source==='reference-fx'?'По оценкам активов и справочному курсу':'Зафиксированная точка старта'}</small></div><div><span>Разница до цели на старте</span><strong>${usd(f.goalGap)}</strong><small>Без предполагаемой доходности</small></div><div><span>Средний прирост по исходному плану / месяц</span><strong>${usd(average)}</strong><small>Требование к цели, не прогноз дохода</small></div></div>${f.fxRate?`<p class="plan-source">Для исходной оценки: ${fmt(f.fxRate,4)} ₽ за USD на ${esc(f.fxDate)}. ${safeLink(f.fxSourceUrl,'Источник курса ↗')} Рыночные оценки жилья и расходы на продажу могут изменить результат.</p>`:''}
 ${f.currentFinancialPeriod?`<div class="notice"><span>Последняя запись (${esc(f.currentFinancialPeriod)}): капитал ${usd(f.currentCapital)}. Средний нужный прирост за оставшийся срок: ${usd(f.remainingRequiredMonthlySurplus)} / мес. Исходные контрольные точки сохраняются.</span></div>`:''}<div class="notice warm"><span>${f.knownIncome!==null&&average!==null&&average>f.knownIncome?`Средний требуемый прирост выше указанного текущего дохода ${usd(f.knownIncome)} в месяц. `:''}Главная проверка ближайших месяцев — появился ли повторяемый доход и свободный денежный поток. При недостаточном темпе пересматриваем способ заработка, срок или сумму цели.</span></div>
 <div class="section-title"><div><div class="eyebrow">ПЯТЬ ФИНАНСОВЫХ КОНТРОЛЬНЫХ ТОЧЕК</div><h3>Какой темп нужен для выбранного срока</h3></div></div><div class="capital-stages">${f.annualCheckpoints.map((p,i)=>`<div class="capital-stage"><span class="capital-dot">${i+1}</span><small>${esc(p.due)}</small><strong>${usd(p.capitalTarget)}</strong></div>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>Дата</th><th>Цель по капиталу</th><th>Нужный свободный поток в этом этапе / мес.</th><th>Нужный ${f.scope==='family'?'семейный':'личный'} доход / мес.</th></tr></thead><tbody>${f.annualCheckpoints.map(p=>`<tr><td>${esc(p.due)}</td><td>${usd(p.capitalTarget)}</td><td>${usd(p.requiredMonthlySurplus)}</td><td>${usd(p.requiredNetIncome)}</td></tr>`).join('')}</tbody></table></div><p class="form-note">Траектория намеренно оставляет время на рост: по этапам закрывается 5%, ещё 10%, 20%, 30% и 35% разницы до цели. Это выбранная схема планирования. Доход = нужный свободный поток + известные ${f.scope==='family'?'семейные':'личные'} расходы. Пока расходы не заполнены, доход не выдумывается.</p>
 <details class="plan-settings"><summary>Исходные данные и допущения маршрута</summary><form id="plan-form"><div class="fields-grid"><label>Рублей за 1 USD<input name="planFxRate" type="number" min="0.01" max="10000" step="0.0001" value="${esc(state.answers.planFxRate||f.fxRate)}" placeholder="Например, курс на дату оценки"></label><label>Дата курса<input name="planFxDate" type="date" value="${esc(state.answers.planFxDate||f.fxDate)}" max="${dateKey()}"></label><label>Или чистый стартовый капитал сразу в USD<input name="planStartingCapital" type="number" min="-1000000000000" max="1000000000000" step="0.01" value="${esc(state.answers.planStartingCapital)}" placeholder="Необязательная ручная оценка"><small>Эта сумма имеет приоритет над пересчётом активов.</small></label><label>Дата начала финансового плана<input name="planStartDate" type="date" required max="${dateKey()}" value="${esc(plan.planStartDate)}"></label></div><button class="button secondary space-top" type="submit">Пересчитать и зафиксировать ориентиры</button></form><ul class="context-questions">${plan.assumptions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:''}
 <div class="section-title space-top"><div><div class="eyebrow">МОЯ БЛИЖАЙШАЯ ТОЧКА · ${esc(horizons.find(x=>x.id===horizon)?.label||'')}</div><h2>Что должно произойти на этом этапе</h2></div></div><div class="personal-checkpoints">${selected.map(p=>`<article class="personal-checkpoint ${state.milestones[p.id]?'complete':''}"><div class="section-title"><div><small>До ${esc(p.due)}</small><h3>${esc(p.title)}</h3></div><label class="milestone-toggle"><input type="checkbox" data-milestone="${esc(p.id)}" ${state.milestones[p.id]?'checked':''}><span>Выполнено</span></label></div><p>${esc(p.action)}</p><ul>${p.acceptance.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${p.capitalTarget!==null?`<div class="checkpoint-money"><span>Ориентир капитала <b>${usd(p.capitalTarget)}</b></span><span>Нужный прирост / мес. <b>${usd(p.requiredMonthlySurplus)}</b></span></div>`:''}</article>`).join('')}</div>
 <div class="plan-choice"><div class="eyebrow">${plan.focus.chosenByUser?'ВЫБРАННОЕ ВАМИ НАПРАВЛЕНИЕ':'СТАРТОВАЯ ГИПОТЕЗА НА ОСНОВЕ ВАШЕГО ОПЫТА'}</div><h3>${esc(plan.focus.label)}</h3><p>${esc(plan.focus.reason)}</p><p><b>Следующий шаг:</b> ${esc(plan.focus.nextStep)}</p><label>Мой конкретный следующий шаг<textarea rows="2" data-answer="planNextStep" maxlength="10000" placeholder="Одно действие на ближайшие 45 минут">${esc(state.answers.planNextStep)}</textarea></label><details><summary>Когда менять подход</summary><ul class="context-questions">${plan.focus.pivotEvidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></div>
 <details class="plan-settings"><summary>Почему этот маршрут подходит именно вам</summary>${plan.factBasis.map(x=>`<article class="plan-fact"><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p>${safeLink(x.url,'Ваша исходная заметка ↗')}</article>`).join('')}<p class="form-note">Учитываются ваши ответы, оценки активов, опыт IT и предпринимательства, доступное время и важность качества жизни. Развёрнутые ответы не интерпретируются скрытым алгоритмом; они сохраняются для следующего осмысленного пересмотра плана.</p></details></section>`;
}
function moodChart() {
 const dates=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);return dateKey(d);});
 const values=dates.map(d=>state.entries[d]?.mood??null),count=values.filter(v=>v!==null).length;
 if(!count)return empty('Пока здесь чистый лист.<br>Первое наблюдение появится после вашей отметки дня.',`<button class="text-button" data-view="today">Отметить состояние →</button>`);
 let lines='',dots='';
 values.forEach((v,i)=>{if(v===null)return;const x=30+i*29,y=150-v*12;if(i&&values[i-1]!==null)lines+=`<path d="M${x-29} ${150-values[i-1]*12} L${x} ${y}"/>`;dots+=`<circle cx="${x}" cy="${y}" r="4"><title>${dayLabel(dates[i])}: ${v}/10</title></circle>`;});
 return `<svg class="mood-chart" viewBox="0 0 435 190" role="img" aria-label="Настроение за 14 дней. Число наблюдений: ${count}">${[0,5,10].map(v=>`<line x1="25" x2="420" y1="${150-v*12}" y2="${150-v*12}" stroke="#e9ece4"/><text x="2" y="${154-v*12}" fill="#7d8678" font-size="10">${v}</text>`).join('')}<g stroke="#497157" stroke-width="2.5" fill="none">${lines}</g><g fill="#497157">${dots}</g><text x="25" y="180" fill="#7d8678" font-size="10">${dayLabel(dates[0])}</text><text x="350" y="180" fill="#7d8678" font-size="10">${dayLabel(dates[13])}</text></svg><p class="form-note">Оценок настроения: ${count} из 14 дней.</p>`;
}
function assetDraftView() {
 const a=context?.assetDraft;if(!a?.items)return '';
 return `<details class="card asset-draft space-top"><summary>Ваша исходная оценка активов · ${fmt(a.items.reduce((s,x)=>s+x.amount,0))} ₽</summary><p class="muted">Из ваших ответов: семейная цель, долгов и ипотек нет. ${fmt(a.items.reduce((s,x)=>s+x.amount,0))} ₽ — предварительная оценка семейного капитала до возможных расходов на продажу. Из них ${fmt(a.liquidAmount)} ₽ наличными; стоимость квартир не является ликвидным резервом.</p><div class="table-wrap"><table><tbody>${a.items.map(x=>`<tr><td>${esc(x.title)}<small>${esc(x.note)}</small></td><td>${fmt(x.amount)} ₽</td></tr>`).join('')}</tbody></table></div><p>Для цели в долларах укажите курс и дату оценки. Калькулятор покажет масштаб задачи без предположений о доходности или росте стоимости жилья. В месячный учёт переносите подтверждённые суммы.</p><form id="fx-form" class="fx-form"><label>Рублей за 1 USD<input type="number" name="rate" min="0.01" step="0.0001" required placeholder="Укажите курс"></label><label>Дата курса<input type="date" name="fxDate" value="${dateKey()}" required max="${dateKey()}"></label><button class="button secondary" type="submit">Рассчитать ориентир</button></form><p id="fx-result" class="form-note" aria-live="polite">Пересчёт справочный; автоматически в капитал не переносится.</p></details>`;
}
function selfView() {
 const g=questionGroups.find(g=>g.id===questionGroup),count=answered(), currencyLocked=Object.keys(state.finances).length>0||['income','expenses','assets','debts','liquidAssets'].some(k=>state.profile[k]!=null);
 return heading('ОПОРА НА СВОИ ЦЕННОСТИ','Познакомимся ближе.','Не экзамен. Можно пропустить любой вопрос и вернуться позже.',`<span class="pill">${count} из ${questionTotal} ответов</span>`)+`
 <section class="card profile-card"><div class="section-title"><div><div class="eyebrow">ТОЧКА НАЗНАЧЕНИЯ</div><h2>Моя цель и мой темп</h2></div></div><form id="profile-form"><div class="three-column"><label>Как к вам обращаться<input name="name" value="${esc(state.profile.name)}" maxlength="100" placeholder="Ваше имя"></label><label>Валюта<select name="currency" ${currencyLocked?'disabled':''}>${[...new Set(['USD','RUB','KZT',state.profile.currency])].map(c=>`<option ${state.profile.currency===c?'selected':''}>${c}</option>`).join('')}</select><small>${currencyLocked?'Зафиксирована, чтобы не смешивать финансовые данные.':'Одна валюта для всего финансового трекера'}</small></label><label>Что считаем целью<select name="goalKind"><option value="capital" ${state.profile.goalKind==='capital'?'selected':''}>Чистый капитал</option><option value="monthlyIncome" ${state.profile.goalKind==='monthlyIncome'?'selected':''}>Чистый доход в месяц</option></select></label><label>Чей финансовый результат<select name="goalScope"><option value="personal" ${state.profile.goalScope==='personal'?'selected':''}>Личный</option><option value="family" ${state.profile.goalScope==='family'?'selected':''}>Семейный</option></select></label><label>Целевая сумма<input name="goalAmount" type="number" min="1" max="1000000000000" required value="${state.profile.goalAmount}"></label><label>К какой дате<input name="goalDate" type="date" required value="${esc(state.profile.goalDate)}"></label><label>Время на шаги, минут в день<input name="dailyMinutes" type="number" min="1" max="1440" required value="${state.profile.dailyMinutes}"></label></div><button class="button primary" type="submit">Сохранить ориентиры</button></form></section>
 ${context?`<details class="card notion-context space-top"><summary>Что я узнал из вашего Notion</summary><p class="muted">${esc(context.scope)}</p>${(context.findings||[]).map(f=>`<article><h3>${esc(f.title)}</h3><p>${esc(f.detail)}</p>${safeLink(f.url,'Открыть источник в Notion ↗')}</article>`).join('')}<h3 class="space-top">Что ещё полезно уточнить</h3><ul class="context-questions">${(context.unresolved||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ul><p class="form-note">Это исходные наблюдения и гипотезы. Ваши сегодняшние ответы имеют приоритет над старыми заметками.</p></details>`:''}
 <section class="questionnaire space-top"><div class="section-title"><div><div class="eyebrow">АНКЕТА БЕЗ СПЕШКИ</div><h2>Понять себя, чтобы выбрать путь</h2></div><span class="muted">Сохраняется автоматически</span></div><div class="progress-track"><span style="width:${count/questionTotal*100}%"></span></div><div class="question-layout"><div class="question-nav" role="group" aria-label="Темы анкеты">${questionGroups.map(gr=>`<button class="${gr.id===questionGroup?'active':''}" data-question-group="${gr.id}"><span>${gr.title}</span><small>${gr.questions.filter(([id])=>state.answers[id]?.trim()).length}/${gr.questions.length}</small></button>`).join('')}</div><div class="card questions"><h2>${g.title}</h2><p class="muted">${g.subtitle}</p>${g.questions.map(([id,q],i)=>`<label class="question"><span class="question-number">${String(i+1).padStart(2,'0')}</span><span>${q}<textarea data-answer="${id}" rows="2" maxlength="10000" placeholder="Ваш ответ, в свободной форме…">${esc(state.answers[id])}</textarea></span></label>`).join('')}<button class="button secondary" data-action="next-group">Следующая тема ${icon('arrow')}</button><p class="form-note">Ответы сохраняются сразу при вводе. Финансовые точки маршрута пересчитываются из ваших чисел; выбранное направление меняет ближайшие действия. После заполнения анкеты можно отдельно пересмотреть смысл ваших ответов и сам план.</p></div></div></section>
 <section class="card space-top data-card"><div><h2>Ваши данные принадлежат вам</h2><p>Ответы автоматически сохраняются в локальной базе на этом компьютере и дублируются в браузере. Надпись «Сохранено в базе» подтверждает запись. В базе хранятся предыдущие версии и ежедневные резервные копии. Между разными компьютерами синхронизации нет.</p></div><div class="data-actions"><button class="button secondary" data-action="export">${icon('download')} Экспорт JSON</button><label class="button secondary file-label">Восстановить из файла<input type="file" id="import-file" accept="application/json,.json"></label><button class="button secondary" data-action="import-text">Вставить JSON</button><button class="text-button" data-action="undo-import">Отменить последний импорт</button>${recoveryRaw?'<button class="text-button" data-action="raw-export">Скачать исходное повреждённое сохранение</button>':''}</div><p class="form-note">Экспорт содержит ваши личные ответы и финансовые записи. Храните файл в личном месте. Перед импортом приложение оставляет предыдущую версию в этом браузере.</p></section>`;
}
function safeLink(url,title) { try {const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return '';return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${title}</a>`;}catch{return '';} }
function methodView() {
 return heading('ДОКАЗАТЕЛЬНОСТЬ И ЗДРАВЫЙ СМЫСЛ','Почему маленькие шаги.','Научная опора, понятные ограничения и право выбирать свой темп.')+`<div class="method-intro"><div class="card"><span class="round-icon">${icon('leaf')}</span><h2>Действие легче обещания</h2><p>Один понятный сигнал, маленькое действие, лёгкая версия на трудный день. Сложность повышается по вашему опыту, а не по календарю.</p></div><div class="card"><span class="round-icon">${icon('heart')}</span><h2>Деньги и хорошая жизнь</h2><p>Доход может расширять возможности. Но отношения, свобода выбора, смысл и отдых требуют собственного внимания.</p></div><div class="card"><span class="round-icon">${icon('chart')}</span><h2>Данные, а не оценка личности</h2><p>Нет общего рейтинга «успешности» и штрафа за пропуски. Наблюдения нужны, чтобы выбрать следующий эксперимент.</p></div></div><div class="section-title space-top"><div><div class="eyebrow">ОТОБРАННЫЕ ИСТОЧНИКИ · ПРОВЕРЕНО 30.09.2026</div><h2>На чём основан подход</h2></div></div><p class="muted">Надёжные работы и рекомендации, включая обновления 2024–2025 годов. Это не исчерпывающий обзор всех новых публикаций.</p><div class="evidence-list">${evidence.map((e,i)=>`<article class="card evidence-card"><span class="source-number">${String(i+1).padStart(2,'0')}</span><div><div class="eyebrow">${esc(e.year)}</div><h3>${safeLink(e.url,esc(e.title)+' ↗')}</h3><p>${esc(e.finding)}</p><p><b>В приложении:</b> ${esc(e.practice)}</p><p class="form-note"><b>Границы:</b> ${esc(e.limitation)}</p></div></article>`).join('')}</div><div class="notice space-top">Вопросы 0–10 в дневнике — авторские ориентиры для наблюдения, не диагностический тест. Если состояние длительно мешает повседневной жизни, трекер может дополнить разговор со специалистом, но не заменить помощь.</div>`;
}
document.addEventListener('click',e=>{
 const t=e.target.closest('button,a[data-view]');if(!t)return;
 if(t.dataset.view){e.preventDefault();go(t.dataset.view);return;}
 if(t.dataset.date){selectedDate=t.dataset.date;render();return;}
 if(t.dataset.horizon){horizon=t.dataset.horizon;render();return;}
 if(t.dataset.questionGroup){questionGroup=t.dataset.questionGroup;render();return;}
 if(t.dataset.focusTrack){state.answers.focusDirection=t.dataset.focusTrack;save('Направление выбрано');render();$('.focus-plan')?.scrollIntoView({behavior:'smooth'});return;}
 if(t.dataset.habitCheck){const id=t.dataset.habitCheck;const entry=state.entries[selectedDate]||{};entry.habits={...entry.habits,[id]:!entry.habits?.[id]};state.entries[selectedDate]=entry;save(entry.habits[id]?'Маленький шаг отмечен':'Отметка отменена');render();return;}
 if(t.dataset.pauseHabit){const h=state.habitPlans.find(x=>x.id===t.dataset.pauseHabit);h.active=!h.active;save();render();return;}
 if(t.dataset.addHabit){if(state.habitPlans.length>=20){toast('Достигнут лимит 20 привычек');return;}const h=habitIdeas.find(x=>x.id===t.dataset.addHabit);const {reason,...plan}=h;state.habitPlans.push({...plan,active:true});save('Привычка добавлена. Частоту можно изменить.');render();return;}
 if(t.dataset.editHabit){editingHabit=t.dataset.editHabit;openHabit();return;}
 if(t.dataset.financeMonth){financeMonth=t.dataset.financeMonth;render();return;}
 switch(t.dataset.action){
  case 'start': $('#daily-steps')?.scrollIntoView({behavior:'smooth',block:'start'});$('.habit-check')?.focus({preventScroll:true});break;
  case 'sync-now': sync?.flush();break;
  case 'sync-local': sync?.resolve('local');break;
  case 'sync-remote': sync?.resolve('remote');break;
  case 'export': dataDialog('export');break;
  case 'import-text': dataDialog('import');break;
  case 'close-data-dialog': $('#data-dialog')?.remove();break;
  case 'download-data': download(JSON.stringify(state,null,2),`small-steps-${dateKey()}.json`);break;
  case 'copy-data': navigator.clipboard?.writeText(JSON.stringify(state,null,2)).then(()=>toast('Резервная копия скопирована')).catch(()=>toast('Выделите текст и скопируйте вручную'));break;
  case 'raw-export': download(corruptRaw||recoveryRaw||JSON.stringify(state,null,2),`small-steps-recovery-${dateKey()}.json`);break;
  case 'new-habit': if(state.habitPlans.length>=20){toast('В трекере уже 20 привычек. Лучше упростить текущие.');break;}editingHabit=null;openHabit();break;
  case 'close-dialog':$('#habit-dialog')?.close();break;
  case 'next-group': questionGroup=questionGroups[(questionGroups.findIndex(x=>x.id===questionGroup)+1)%questionGroups.length].id;render();$('.questionnaire')?.scrollIntoView({behavior:'smooth'});break;
  case 'undo-import':try{const prev=localStorage.getItem(STORAGE_KEY+'-backup');if(!prev){toast('Предыдущая версия не найдена');break;}const s=validateImport(JSON.parse(prev));localStorage.setItem(STORAGE_KEY,JSON.stringify(s));state=s;validSnapshot=JSON.stringify(state);corruptRaw=null;storageIssue='';sync?.queue(state);render();toast('Предыдущая версия восстановлена');}catch(err){toast('Не удалось восстановить: '+err.message);}break;
 }
});
function openHabit() {const dialog=$('#habit-dialog'),form=$('#habit-form');form.reset();if(editingHabit){const h=state.habitPlans.find(x=>x.id===editingHabit);for(const key of ['title','cue','minimum','target'])form.elements[key].value=h[key];}dialog.showModal();}
function updateAnswerCount() {
 if(view!=='self')return;
 const count=answered();
 const counter=$('.page-heading .pill');if(counter)counter.textContent=`${count} из ${questionTotal} ответов`;
 const badge=$('.nav-count');if(badge)badge.textContent=`${count}/${questionTotal}`;
 const progress=$('.progress-track span');if(progress)progress.style.width=`${count/questionTotal*100}%`;
 for(const g of questionGroups){const label=$(`[data-question-group="${g.id}"] small`);if(label)label.textContent=`${g.questions.filter(([id])=>state.answers[id]?.trim()).length}/${g.questions.length}`;}
}
document.addEventListener('input',e=>{
 const t=e.target;
 if(t.dataset.answer){state.answers[t.dataset.answer]=t.value;save('Ответ сохранён');updateAnswerCount();}
});
document.addEventListener('change',async e=>{
 const t=e.target;
 if(t.dataset.answer){state.answers[t.dataset.answer]=t.value;save('Ответ сохранён');updateAnswerCount();return;}
 if(t.dataset.milestone){state.milestones[t.dataset.milestone]=t.checked;save();render();return;}
 if(t.name==='entryDate'){if(t.value&&t.value<=dateKey()){selectedDate=t.value;render();}return;}
 if(t.id==='finance-month'){if(t.value&&t.value<=dateKey().slice(0,7)){financeMonth=t.value;render();}return;}
 if(t.id==='import-file'&&t.files[0]){try{const file=t.files[0];if(file.size>2000000)throw new Error('Файл больше 2 МБ');restoreBackup(await file.text());}catch(err){toast('Импорт не выполнен: '+err.message);} }
});
document.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target, data=Object.fromEntries(new FormData(form));
 if(form.id==='import-text-form'){try{restoreBackup(data.backup);}catch(err){toast('Импорт не выполнен: '+err.message);}return;}
 if(form.id==='checkin-form'){const {entryDate,note,...scores}=data;state.entries[selectedDate]={...state.entries[selectedDate],...Object.fromEntries(Object.entries(scores).map(([k,v])=>[k,num(v)])),note};save('День сохранён. Спасибо за минуту внимания к себе.');render();}
 if(form.id==='plan-form'){for(const [key,value] of Object.entries(data)){state.answers[key]=value.trim();}save('Ориентиры пересчитаны');render();}
 if(form.id==='profile-form'){state.profile={...state.profile,...data,goalAmount:Number(data.goalAmount),dailyMinutes:Number(data.dailyMinutes)};save('Ориентиры обновлены');render();}
 if(form.id==='finance-form'){state.finances[financeMonth]=Object.fromEntries(Object.entries(data).map(([k,v])=>[k,num(v)]));save('Финансовая запись сохранена');render();}
 if(form.id==='review-form'){state.reviews[dateKey()]={...data,...Object.fromEntries(['satisfaction','autonomy','conversations','offers','paidPilots'].map(k=>[k,num(data[k])]))};save('Обзор сохранён. Следующий шаг уже намечен.');render();}
 if(form.id==='habit-form'){if(!editingHabit&&state.habitPlans.length>=20){toast('Достигнут лимит 20 привычек');return;}const h={...data,target:Number(data.target),id:editingHabit||'custom-'+Date.now(),active:editingHabit?state.habitPlans.find(x=>x.id===editingHabit).active:true};if(editingHabit)state.habitPlans=state.habitPlans.map(x=>x.id===editingHabit?h:x);else state.habitPlans.push(h);save();$('#habit-dialog').close();render();}
 if(form.id==='fx-form'){const total=context.assetDraft.items.reduce((s,x)=>s+x.amount,0);$('#fx-result').textContent=`${fmt(total/Number(data.rate))} USD по введённому курсу ${data.rate} ₽/USD на ${data.fxDate}. При семейной цели 1 000 000 USD за 60 месяцев нужно около ${fmt(Math.max(0,1000000-total/Number(data.rate))/60)} USD чистого прироста капитала в месяц, без доходности, изменения цен, курсов и расходов на продажу. Это иллюстрация исходной пятилетней цели. В трекер не перенесена.`;}
});
function download(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function dataDialog(mode) {
 $('#data-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='data-dialog';
 dialog.innerHTML=`<div class="section-title"><h2>${mode==='export'?'Резервная копия':'Восстановить из текста'}</h2><button type="button" class="icon-button" data-action="close-data-dialog" aria-label="Закрыть резервную копию">×</button></div><p class="form-note">${mode==='export'?'Скачайте JSON или скопируйте текст в личный файл. Он содержит ваши финансовые записи и ответы.':'Вставьте ранее сохранённый JSON. Перед заменой мы сохраним предыдущую версию в этом браузере.'}</p><form id="${mode==='import'?'import-text-form':'export-text-form'}"><label>JSON резервной копии<textarea name="backup" rows="10" ${mode==='export'?'readonly':'required'} maxlength="2000000">${mode==='export'?esc(JSON.stringify(state,null,2)):''}</textarea></label><div class="data-actions">${mode==='export'?'<button type="button" class="button primary" data-action="download-data">Скачать файл</button><button type="button" class="button secondary" data-action="copy-data">Скопировать текст</button>':'<button type="submit" class="button primary">Восстановить данные</button>'}</div></form>`;
 document.body.append(dialog);dialog.showModal();
}
function restoreBackup(raw) {
 const parsed=JSON.parse(raw);const next=validateImport(parsed?.state && Number.isSafeInteger(parsed.revision)?parsed.state:parsed);const wasCorrupt=!!corruptRaw;
 if(corruptRaw){localStorage.setItem(STORAGE_KEY+'-recovery',corruptRaw);recoveryRaw=corruptRaw;}
 localStorage.setItem(STORAGE_KEY+'-backup',JSON.stringify(state));localStorage.setItem(STORAGE_KEY,JSON.stringify(next));
 state=next;validSnapshot=JSON.stringify(state);corruptRaw=null;storageIssue='';if(wasCorrupt)sync?.start(state,{hasLocal:true});else sync?.queue(state);$('#data-dialog')?.remove();render();toast('Данные восстановлены. Предыдущая версия сохранена.');
}
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(nav.some(n=>n[0]===v)&&v!==view){view=v;render();}});
render();
